import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FloatingParticles from "./_components/FloatingParticles";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "weaver",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="overflow-hidden relative mx-auto w-screen max-w-none h-screen max-md:h-screen max-md:max-w-[991px] max-sm:max-w-screen-sm">{children}</div>
        <FloatingParticles />
      </body>
    </html>
  );
}
